version: '3'

services:
  nest-api:
    image: ghcr.io/virtual-academic-affair/nest-api:latest
    container_name: nest-api-container
    restart: always
    ports:
      - "80:3000"
      - "443:3000"
      - "5000:5000"
    env_file:
      - .env

networks:
  nest-network:
    driver: bridge