syntax = "proto3";
package app_server;
import "google/protobuf/empty.proto";

message SuccessResponse {
  bool success = 1;
}

// --- Message Label Domain ---
message UpdateLabelRequest {
  int32 messageId = 1;
  string systemLabel = 2;
  bool isRemove = 3;
}

service MessageLabelService {
  rpc UpdateLabel(UpdateLabelRequest) returns (SuccessResponse);
}

// --- Auth Domain ---
message UserResponse {
  int32 id = 1;
  string email = 2;
  string name = 3;
  string role = 4;
  string picture = 5;
  bool isActive = 6;

  string createdAt = 7;
  string updatedAt = 8;
}

service AuthService {
  rpc Me(google.protobuf.Empty) returns (UserResponse);
}

// --- Task Domain ---
message CreateTaskRequest {
  int32 messageId = 1;
}

service TaskService {
  rpc Create(CreateTaskRequest) returns (SuccessResponse);
}

// --- Inquiry Domain ---
message CreateInquiryRequest {
  int32 messageId = 1;
}

service InquiryService {
  rpc Create(CreateInquiryRequest) returns (SuccessResponse);
}

// --- Class Registration Domain ---
message CreateRegistrationRequest {
  int32 messageId = 1;
}

service ClassRegistrationService {
  rpc Create(CreateRegistrationRequest) returns (SuccessResponse);
}
